SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 560
VELOCITY_MIN = 13
VELOCITY_MAX = 20
SPEED_MULTIPLIER = 1
SPEED_MULTIPLIER_MEDIUM = 1.5
SPEED_MULTIPLIER_HARD = 2
SPAWN_PADDING = 10
PLAYER_SPEED = 15
PLAYER_LIVES = 3
MIN_OBSTACLE_GAP = 400
BOARD_SPEED = 7
LASER_SCALE_TUPLE = (32, 96)
FASTER_LASER_SCALE_TUPLE = (28, 140)
LASER_RESPAWN = [500, 600, 700, 1000, 2000, 3000]
BACKGROUND_IMG = "src/background/background.png"
PLAYER_IMG = "src/player/player.png"
LASER_IMG = "src/laser/laser.png"
FAST_LASER_IMG = "src/laser/laserblue.png"
FONT = "src/font/Pixeltype.ttf"
AUDIO_TRACK = "src/audio/0.wav"
GAME_OVER_AUDIO = "src/audio/1.wav"
OBSTACLE_IMG = "src/obstacle/pillar.png"
PLAYER_HIT_AUD = "src/audio/2.ogg"
PLAY_AGAIN_STR = "Press SPACE to play again"
LEVEL_CHOICE_STR = "1. Easy    2. Medium    3. Hard"