SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
VELOCITY_MIN = 13
VELOCITY_MAX = 20
SPEED_MULTIPLIER = 1
SPEED_MULTIPLIER_FASTER = 1.5
SPAWN_PADDING = 10
PLAYER_SPEED = 15
PLAYER_LIVES = 3
LASER_SCALE_TUPLE = (32, 96)
FASTER_LASER_SCALE_TUPLE = (28, 140)
BACKGROUND_IMG = "src/background/background.png"
PLAYER_IMG = "src/player/player.png"
LASER_IMG = "src/laser/laser.png"
FAST_LASER_IMG = "src/laser/laserblue.png"
FONT = "src/font/Pixeltype.ttf"
AUDIO_TRACK = "src/audio/0.wav"
GAME_OVER_AUDIO = "src/audio/1.wav"
PLAY_AGAIN_STR = "Press SPACE to play again"
LEVEL_CHOICE_STR = "1. Easy    2. Medium    3. Hard"